First Cimmit
RuS984/react-burger pull request #1
Opened 2024-02-22 01:10 UTC by RuS984

2024-02-22 09:35 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;

### **Но есть несколько замечаний, которые нужно исправить:**

- В файлах, где содержится `jsx`, нужно поменять расширение с `.js` на `.jsx`;

- Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app.

  - App.test.tsx

- В компоненте App-header требуется поправить семантику. Иконка и текст должны быть обёрнуты в ссылку, нужно переделать `span` в ссылки.

- В директории `components` должен быть компонент App. Компонент `App`, он также должен быть в папке (как и другие компоненты). Как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов;

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили. Нужно исправить во всём проекте: <https://disk.yandex.com/i/Y2mg_PiyBgdILw>;

- Нужно поправить верстку:

  - <https://disk.yandex.com/i/Pb3RmMhSIPWAMg> - шрифт тут вроде бы должен быть другой, а также добавьте расстояние между элементами. Отступы нужно делать с помощью flex/grid модели, либо с помощью margin. Не стоит делать отступы с помощью дополнительных элементов;

  - <https://disk.yandex.com/i/AQzCRNIOxAtY8w> - Булки должны оставаться на месте, а скролл должен быть только у ингредиентов. Ещё раз сверьтесь с дизайном - <https://disk.yandex.com/i/O9pbWtLvN-VTBQ>;

- <https://disk.yandex.com/i/uvN4zPNBZHt7rQ> - Нужно исправить все ошибки в консоли браузера;

- Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
  ```

  Проверьте во всём проекте.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь <https://learn.javascript.ru/coding-style>. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (<https://prettier.io/>)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2024-02-22 09:35 UTC, ArslanMustafin commented on src/App.js
> +  });
**Надо исправить:**

Вам пока не нужен этот массив.

Лучше изначально разделить булку и ингредиенты:

```js
// Компонент burger-constructor
const { bun, ingredients } = useMemo(() => {
  return {
    bun: data.find(item => item.type === 'bun'),
    ingredients: data.filter(item => item.type !== 'bun'),
  };
}, [data]);
```

в будущем вам это пригодится)

2024-02-22 09:35 UTC, ArslanMustafin commented on src/App.js
> +  },[]);
**Надо исправить:**

Добавьте проверку ответа сервера - res.ok:

Например:

```js
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответит не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```js
const checkResponse = res => {
  return res.ok ? res.json() : res.json().then(err => Promise.reject(err));
};
```

`fetch(someUrl).then(checkResponse)`

<!--  -->

**Можно лучше:**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```js
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}
```

и разместить их в отдельном файле `utils/burger-api.js`, а не описывать запросы в самом компоненте

```jsx
// использование
getIngredients()
  .then(setState)
  .catch(...)
  .finally()
```

2024-02-22 09:35 UTC, ArslanMustafin commented on src/components/AppHeader/AppHeader.jsx
> +                </span>
**Надо исправить:**

не нужно выносить каждую ссылку в отдельный компонент - `ConstructorButton`, `OrderFeed`, `MyAccount`.
Лучше разместить всё в этом компоненте.

2024-02-22 09:35 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +        return sum + current.price;}, 0) : 0;
**можно лучше:**

Не стоит делать проверку `selectedIngredients` на `undefined`. selectedIngredients - это массив, поэтому проверку нужно делать на свойство `length`. Ну и в данном случае, проверка не нужна, даже если массив будет пустым, `reduce` просто возьмёт начальное значение acc.

2024-02-22 09:35 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +                    {selectedIngredients !== undefined ? selectedIngredients.map((selectedIngredient, index) =>
**можно лучше:**

лучше написать так:  `!!selectedIngredients.length && selectedIngredients.map(...)`

2024-02-22 09:35 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    selectedIngredients: PropTypes.arrayOf(propTypesburgerIngredients).isRequired
**Надо исправить:**

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientType.isRequired).isRequired;
```

2024-02-22 09:35 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructorElement.jsx
> +class BurgerConstructorElement extends React.Component {
**Можно лучше:**

Используйте функциональные компоненты, а не классовые. Сейчас при разработке на React стремятся отдавать предпочтение функциональным компонентам, эти компоненты в проекте можно легко переписать как функциональные с использованием хуков.

2024-02-22 09:35 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredient.jsx
> +    ingredient: PropTypes.arrayOf(propTypesburgerIngredients).isRequired,
**Надо исправить:**

неправильно указан тип пропса, тут нужно указать `propTypesburgerIngredients.isRequired`

2024-02-22 09:35 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +    const filteredIngredientMain = burgerIngredients !== undefined ? burgerIngredients.filter(item => item.type === 'main') : [];
**Можно лучше:**

тут не нужна проверка на `undefined`

2024-02-22 09:35 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredientsPropType.js
> +});
**Надо исправить:**

всем полям нужно добавить `.isRequired`

2024-02-22 22:36 UTC, RuS984 commented on src/components/AppHeader/AppHeader.jsx
> +                </span>
Выполнено

2024-02-22 22:37 UTC, RuS984 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +        return sum + current.price;}, 0) : 0;
Выполнено

2024-02-24 14:18 UTC, RuS984 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    selectedIngredients: PropTypes.arrayOf(propTypesburgerIngredients).isRequired
Выполнено

2024-02-25 16:01 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Хорошая работа!

### **Вы молодец!.**

- Большинство замечания были исправлены;

### **Но есть несколько замечаний, которые нужно исправить:**

- В компоненте App-header требуется поправить семантику. Иконка и текст должны быть обёрнуты в ссылку, нужно переделать `span` в ссылки.

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили. Нужно исправить во всём проекте: <https://disk.yandex.com/i/Y2mg_PiyBgdILw>;

- Нужно поправить верстку:

  - <https://disk.yandex.com/i/ogdtA3ocyjygWw> - Растяните ингредиенты на всю ширину экрана;
  - <https://disk.yandex.com/i/DZ7v4__27SX9DA> - У булок не должно быть этих иконок;

- <https://disk.yandex.com/i/uvN4zPNBZHt7rQ> - Нужно исправить все ошибки в консоли браузера;

- <https://disk.yandex.com/i/QoRqwg3ZJkrlLA> - Модальное окно должно закрываться по клику на оверлей.

- Нужно исправить следующие замечания:
  - <https://github.com/RuS984/react-burger/pull/1#discussion_r1498913092>
  - <https://github.com/RuS984/react-burger/pull/1#discussion_r1498916507>
  - <https://github.com/RuS984/react-burger/pull/1#discussion_r1498938165>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2024-02-25 16:01 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    selectedIngredients !== undefined ? selectedIngredients.slice(1, -1) : [];
**Надо исправить:**

Лучше разделить булку и ингредиенты таким образом:

```js
const { bun, ingredients } = useMemo(() => {
  return {
    bun: data.find(item => item.type === 'bun'),
    ingredients: data.filter(item => item.type !== 'bun'),
  };
}, [selectedIngredients]);
```

2024-02-25 16:01 UTC, ArslanMustafin commented on src/components/Modal/Modal.jsx
> +      <ModalOverlay handleCloseClick={() => handleClickClose} />
**Можно лучше:**

Лучше написать так: `<ModalOverlay handleCloseClick={handleClickClose} />`

2024-02-25 16:01 UTC, ArslanMustafin commented on src/components/IngredientDetails/IngredientDetails.jsx
> +    <Modal
**Надо исправить:**

вы не должны использовать тут `Modal`.  IngredientsDetails это контент, для модального окна, в нём не должно быть компонента `Modal`.

вам нужно вложить `IngredientDetails` в компонент `Modal`.

```js
{isOpen && (
  <Modal handleClickClose={handleCloseModal} title={"Детали ингредиента"} >
          <IngredientDetails ... />
  </Modal>}
```

2024-02-25 16:01 UTC, ArslanMustafin commented on src/components/IngredientDetails/IngredientDetails.jsx
> +      isOpenModal={isOpenModal}
**Надо исправить:**

тут не должно быть этого пропса, вы ведь его не используете))

2024-02-27 13:48 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа!

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

2024-02-27 13:48 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +          text={bun.name}
**Можно лучше:**

По макету у булок должна быть приписка `(верх)` и `(низ)`.

2024-02-27 13:48 UTC, ArslanMustafin commented on src/components/App/App.jsx
> +      "https://norma.nomoreparties.space/api/ingredients",
**Можно лучше:**

вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

2024-03-05 20:23 UTC, merged